// Generated by CoffeeScript 2.3.1
(function() {
  var File;

  File = class File {
    constructor(docDir, srcDir, srcPath) {
      this.docDir = docDir;
      this.docPath = null;
      this.srcDir = srcDir;
      this.srcPath = srcPath;
      this.raw = null;
      this.text = null;
      this.content = null;
      this.type = null;
      this.frontMatter = null;
      this.categories = null;
      this.tags = null;
      this.excerpt = null;
      this.more = null;
    }

  };

  module.exports = File;

}).call(this);
