// Generated by CoffeeScript 2.3.1
(function() {
  var Generator;

  module.exports = Generator = class Generator {
    constructor(logger) {
      // fn: param page, pages, return Promise
      this.register = this.register.bind(this);
      this.generate = this.generate.bind(this);
      this.logger = logger;
      this.store = {};
    }

    register(layout, fn) {
      var i, l, len;
      if (layout instanceof Array) {
        for (i = 0, len = layout.length; i < len; i++) {
          l = layout[i];
          this.store[l] = fn;
        }
        return;
      }
      return this.store[layout] = fn;
    }

    generate(page, posts) {
      if (page["layout"] in this.store) {
        return this.store[page["layout"]](page, posts);
      }
      return page;
    }

  };

}).call(this);
