// Generated by CoffeeScript 2.3.1
(function() {
  var Generator;

  module.exports = Generator = class Generator {
    constructor(logger) {
      // fn: param page, pages, ctx, return Promise
      this.register = this.register.bind(this);
      this.generate = this.generate.bind(this);
      this.logger = logger;
      this.store = {};
    }

    register(layout, fn) {
      var i, l, len;
      if (layout instanceof Array) {
        for (i = 0, len = layout.length; i < len; i++) {
          l = layout[i];
          if (fn instanceof Function) {
            this.store[l] = {
              "layout": l,
              "fn": fn
            };
          }
        }
        return;
      }
      if (fn instanceof Function) {
        return this.store[layout] = {
          "layout": layout,
          "fn": fn
        };
      }
    }

    generate(page, posts, ctx) {
      var layout;
      layout = page["layout"] || "page";
      if (layout in this.store) {
        return this.store[layout]["fn"](page, posts, ctx);
      }
      return page;
    }

  };

}).call(this);
