// Generated by CoffeeScript 2.3.1
(function() {
  //!/usr/bin/env coffee
  var Hikaru, commander, packageJSON;

  packageJSON = require("../package.json");

  commander = require("commander");

  Hikaru = require("./hikaru");

  commander.version(packageJSON["version"]).usage("<subcommand> [options] [dir]").description(packageJSON["description"]);

  commander.command("init [dir]").alias("i").option("-g, --debug", "Print debug messages.").option("-c, --config <yml>", "Alternative config path.").option("-s, --srcDir <dir>", "Alternative src dir.").option("-d, --docDir <dir>", "Alternative doc dir.").option("-t, --themeDir <dir>", "Alternative theme dir.").action(function(dir, cmd) {
    return new Hikaru(cmd["debug"]).init(dir || ".", cmd["config"], cmd["srcDir"], cmd["docDir"], cmd["themeDir"]);
  });

  commander.command("clean [dir]").alias("c").option("-g, --debug", "Print debug messages.").option("-c, --config <yml>", "Alternative config path.").option("-d, --docDir <dir>", "Alternative doc dir.").action(function(dir, cmd) {
    return new Hikaru(cmd["debug"]).clean(dir || ".");
  });

  commander.command("generate [dir]").alias("g").option("-g, --debug", "Print debug messages.").option("-c, --config <yml>", "Alternative config path.").option("-s, --srcDir <dir>", "Alternative src dir.").option("-d, --docDir <dir>", "Alternative doc dir.").option("-t, --themeDir <dir>", "Alternative theme dir.").action(function(dir, cmd) {
    return new Hikaru(cmd["debug"]).generate(dir || ".", cmd["config"], cmd["srcDir"], cmd["docDir"], cmd["themeDir"]);
  });

  commander.parse(process.argv);

}).call(this);
