// Generated by CoffeeScript 2.3.1
(function() {
  var Logger, colors;

  colors = require("colors/safe");

  module.exports = Logger = class Logger {
    constructor(debug) {
      this.isDebug = debug;
    }

    info(...strs) {
      return console.log(colors.yellow("INFO:"), ...strs);
    }

    debug(...strs) {
      if (this.isDebug) {
        return console.debug(colors.green("DEBUG:"), ...strs);
      }
    }

    error(...strs) {
      return console.log(colors.red("ERROR:"), ...strs);
    }

  };

}).call(this);
