// Generated by CoffeeScript 2.3.1
(function() {
  var Logger;

  module.exports = Logger = class Logger {
    constructor(debug) {
      this.isDebug = debug;
    }

    info(...strs) {
      return console.log("INFO:", ...strs);
    }

    debug(...strs) {
      if (this.isDebug) {
        return console.debug("DEBUG:", ...strs);
      }
    }

    error(...strs) {
      return console.log("ERROR:", ...strs);
    }

  };

}).call(this);
