// Generated by CoffeeScript 2.3.1
(function() {
  var Processer, colors;

  colors = require("colors/safe");

  module.exports = Processer = class Processer {
    constructor(logger) {
      // fn: param p, posts, ctx, return Promise
      this.register = this.register.bind(this);
      this.process = this.process.bind(this);
      this.logger = logger;
      this._ = {};
    }

    register(layout, fn) {
      var i, l, len;
      if (!(fn instanceof Function)) {
        throw new TypeError("fn must be a Function!");
        return;
      }
      if (layout instanceof Array) {
        for (i = 0, len = layout.length; i < len; i++) {
          l = layout[i];
          this._[l] = {
            "layout": l,
            "fn": fn
          };
        }
        return;
      }
      return this._[layout] = {
        "layout": layout,
        "fn": fn
      };
    }

    process(p, posts, templates, ctx) {
      this.logger.debug(`Hikaru is processing \`${colors.cyan(p["docPath"])}\`...`);
      if (p["layout"] in this._) {
        return this._[p["layout"]]["fn"](p, posts, ctx);
      }
      return Object.assign({}, p, ctx);
    }

  };

}).call(this);
