// Generated by CoffeeScript 2.3.1
(function() {
  var Renderer, path;

  path = require("path");

  module.exports = Renderer = class Renderer {
    constructor(logger) {
      // fn: param text, fullPath, ctx, return Promise
      this.register = this.register.bind(this);
      this.render = this.render.bind(this);
      this.logger = logger;
      this.store = {};
    }

    register(srcExt, fn) {
      if (srcExt instanceof Object) {
        this.store[srcExt["srcExt"]] = srcExt["fn"];
        return;
      }
      return this.store[srcExt] = fn;
    }

    render(text, fullPath, ctx) {
      var srcExt;
      srcExt = path.extname(fullPath);
      if (srcExt in this.store) {
        return this.store[srcExt](text, fullPath, ctx);
      }
      return null;
    }

  };

}).call(this);
