// Generated by CoffeeScript 2.3.1
(function() {
  var Router, Translator, dateStrCompare, fm, fse, getAbsPathFn, getURLFn, glob, isCurrentPathFn, moment, path, yaml;

  path = require("path");

  fm = require("front-matter");

  fse = require("fs-extra");

  yaml = require("js-yaml");

  glob = require("glob");

  moment = require("moment");

  Translator = require("./translator");

  ({dateStrCompare, getAbsPathFn, getURLFn, isCurrentPathFn} = require("./utils"));

  module.exports = Router = class Router {
    constructor(logger, renderer, generator, translator, site) {
      // fn: param site, change site.
      this.register = this.register.bind(this);
      this.readData = this.readData.bind(this);
      this.writeData = this.writeData.bind(this);
      this.routeThemeAssets = this.routeThemeAssets.bind(this);
      this.routeTemplates = this.routeTemplates.bind(this);
      this.routeSrcs = this.routeSrcs.bind(this);
      this.route = this.route.bind(this);
      this.logger = logger;
      this.renderer = renderer;
      this.generator = generator;
      this.translator = translator;
      this.site = site;
      this.store = {
        "beforeGenerating": [],
        "afterGenerating": []
      };
    }

    register(type, fn) {
      if (!(type in this.store)) {
        return;
      }
      if (fn instanceof Function) {
        return this.store[type].push(fn);
      }
    }

    matchFiles(pattern, options) {
      return new Promise(function(resolve, reject) {
        return glob(pattern, options, function(err, res) {
          if (err) {
            return reject(err);
          }
          return resolve(res);
        });
      });
    }

    readData(srcDir, srcPath) {
      this.logger.debug(`Hikaru is reading \`${path.join(srcDir, srcPath)}\`...`);
      return fse.readFile(path.join(srcDir, srcPath), "utf8").then(function(raw) {
        return {
          "srcPath": srcPath,
          "text": raw,
          "raw": raw
        };
      });
    }

    writeData(srcDir, data) {
      this.logger.debug(`Hikaru is writing \`${path.join(this.site["docDir"], data["docPath"])}\`...`);
      if (data["content"] != null) {
        return fse.outputFile(path.join(this.site["docDir"], data["docPath"]), data["content"]);
      }
      return fse.copy(path.join(srcDir, data["srcPath"]), path.join(this.site["docDir"], data["docPath"]));
    }

    routeThemeAssets() {
      return this.matchFiles(path.join("**", "*"), {
        "nodir": true,
        "dot": true,
        "cwd": this.site["themeSrcDir"]
      }).then((themeSrcs) => {
        return themeSrcs.filter(function(srcPath) {
          // Asset is in sub dir.
          return path.dirname(srcPath) !== ".";
        }).map((srcPath) => {
          return this.readData(this.site["themeSrcDir"], srcPath).then((data) => {
            return this.renderer.render(data, null);
          }).then((data) => {
            return this.writeData(this.site["themeSrcDir"], data);
          });
        });
      });
    }

    routeTemplates() {
      return this.matchFiles("*", {
        "nodir": true,
        "dot": true,
        "cwd": this.site["themeSrcDir"]
      }).then((templates) => {
        return Promise.all(templates.map((srcPath) => {
          return this.readData(this.site["themeSrcDir"], srcPath).then((data) => {
            return this.site["templates"][path.basename(srcPath, path.extname(srcPath))] = this.renderer.render(data, null);
          });
        }));
      });
    }

    routeSrcs() {
      return this.matchFiles(path.join("**", "*"), {
        "nodir": true,
        "dot": true,
        "cwd": this.site["srcDir"]
      }).then((srcs) => {
        var j, len, renderedPromises, srcPath;
        renderedPromises = [];
        for (j = 0, len = srcs.length; j < len; j++) {
          srcPath = srcs[j];
          ((srcPath) => {
            return renderedPromises.push(this.readData(this.site["srcDir"], srcPath).then((data) => {
              var parsed;
              if (typeof data["raw"] === "string") {
                parsed = fm(data["raw"]);
                data["text"] = parsed["body"];
                data = Object.assign(data, parsed["attributes"]);
                if (data["text"] !== data["raw"]) {
                  if (data["title"] != null) {
                    data["title"] = data["title"].toString();
                  }
                  return this.renderer.render(data, null);
                }
              }
              this.renderer.render(data, null).then((data) => {
                return this.writeData(this.site["srcDir"], data);
              });
              return null;
            }));
          })(srcPath);
        }
        return Promise.all(renderedPromises);
      });
    }

    generateAll(ps) {
      var err, generated, j, lang, language, len, p;
      generated = [];
      for (j = 0, len = ps.length; j < len; j++) {
        p = ps[j];
        lang = p["language"] || this.site["siteConfig"]["language"];
        if (!(lang in this.translator.list())) {
          try {
            language = yaml.safeLoad(fse.readFileSync(path.join(this.site["themeDir"], "languages", `${lang}.yml`)));
            this.translator.register(lang, language);
          } catch (error) {
            err = error;
            null;
          }
        }
        p = this.generator.generate(p, this.site["posts"], {
          "site": this.site,
          "siteConfig": this.site["siteConfig"],
          "themeConfig": this.site["themeConfig"],
          "moment": moment,
          "getURL": getURLFn(this.site["siteConfig"]["baseURL"], this.site["siteConfig"]["rootDir"]),
          "getAbsPath": getAbsPathFn(this.site["siteConfig"]["rootDir"]),
          "isCurrentPath": isCurrentPathFn(this.site["siteConfig"]["rootDir"], p["docPath"]),
          "__": this.translator.getTranslateFn(lang)
        });
        if (!(p instanceof Array)) {
          generated.push(p);
        } else {
          generated = generated.concat(p);
        }
      }
      return generated;
    }

    route() {
      this.routeThemeAssets();
      return this.routeTemplates().then(() => {
        return this.routeSrcs();
      }).then(async(renderedPages) => {
        var data, fn, i, j, k, l, len, len1, len2, len3, len4, len5, m, n, o, p, page, post, q, ref, ref1, ref2, ref3, ref4, ref5, results;
        for (j = 0, len = renderedPages.length; j < len; j++) {
          p = renderedPages[j];
          if (p == null) {
            continue;
          }
          if (p["layout"] === "post") {
            this.site["posts"].push(p);
          } else {
            if (!(p["layout"] in this.site["templates"])) {
              p["layout"] = "page";
            }
            this.site["pages"].push(p);
          }
        }
        // Posts.
        this.site["posts"].sort(dateStrCompare);
        ref = this.store["beforeGenerating"];
        // Custum route.
        for (k = 0, len1 = ref.length; k < len1; k++) {
          fn = ref[k];
          this.site = fn(this.site);
        }
        this.site["posts"] = this.generateAll(this.site["posts"]);
        for (i = l = 0, ref1 = this.site["posts"].length; (0 <= ref1 ? l < ref1 : l > ref1); i = 0 <= ref1 ? ++l : --l) {
          if (i > 0) {
            this.site["posts"][i]["next"] = this.site["posts"][i - 1];
          }
          if (i < this.site["posts"].length - 1) {
            this.site["posts"][i]["prev"] = this.site["posts"][i + 1];
          }
        }
        // Pages.
        this.site["pages"] = this.generateAll(this.site["pages"]);
        ref2 = this.store["afterGenerating"];
        for (m = 0, len2 = ref2.length; m < len2; m++) {
          fn = ref2[m];
          this.site = fn(this.site);
        }
        ref3 = this.site["pages"];
        for (n = 0, len3 = ref3.length; n < len3; n++) {
          page = ref3[n];
          page["content"] = (await this.site["templates"][page["layout"]](page));
          this.writeData(this.site["srcDir"], page);
        }
        ref4 = this.site["posts"];
        // Merge post and template last.
        for (o = 0, len4 = ref4.length; o < len4; o++) {
          post = ref4[o];
          post["content"] = (await this.site["templates"][post["layout"]](post));
          this.writeData(this.site["srcDir"], post);
        }
        ref5 = this.site["data"];
        results = [];
        for (q = 0, len5 = ref5.length; q < len5; q++) {
          data = ref5[q];
          results.push(this.writeData(this.site["srcDir"], data));
        }
        return results;
      });
    }

  };

}).call(this);
