// Generated by CoffeeScript 2.3.1
(function() {
  var Translator, vsprintf;

  ({vsprintf} = require("sprintf-js"));

  module.exports = Translator = class Translator {
    constructor(language) {
      this.__ = this.__.bind(this);
      this._p = this._p.bind(this);
      this.language = language;
    }

    __(key) {
      var i, k, keys, len, res;
      keys = key.toString().split(".");
      res = this.language;
      for (i = 0, len = keys.length; i < len; i++) {
        k = keys[i];
        if (!(k in res)) {
          return key;
        }
        res = res[k];
      }
      if (typeof res === "string") {
        return res;
      }
      return key;
    }

    _p(key, ...args) {
      var i, k, keys, len, res;
      keys = key.toString().split(".");
      res = this.language;
      for (i = 0, len = keys.length; i < len; i++) {
        k = keys[i];
        if (!(k in res)) {
          return key;
        }
        res = res[k];
      }
      if (typeof res === "string") {
        return vsprintf(res, args);
      }
      return vsprintf(key, args);
    }

  };

}).call(this);
